"""create videos table

Revision ID: 655b56f74310
Revises: 2be3de7b9208
Create Date: 2022-04-14 16:01:21.597078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '655b56f74310'
down_revision = '2be3de7b9208'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channelId', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=50000), nullable=True),
    sa.Column('videoUrl', sa.String(length=255), nullable=False),
    sa.Column('thumbnailUrl', sa.String(length=255), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['channelId'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videos')
    # ### end Alembic commands ###
