"""add channelTrailerId column to channels table

Revision ID: 2be3de7b9208
Revises: fe92cd5305bd
Create Date: 2022-04-14 14:41:30.997151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2be3de7b9208'
down_revision = 'fe92cd5305bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('channelTrailerId', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'channelTrailerId')
    # ### end Alembic commands ###
