"""add bannerImageUrl column to channels table

Revision ID: fe92cd5305bd
Revises: 9944ff8ea469
Create Date: 2022-04-13 18:38:13.124454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe92cd5305bd'
down_revision = '9944ff8ea469'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('bannerImageUrl', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'bannerImageUrl')
    # ### end Alembic commands ###
