"""create channels table

Revision ID: 9944ff8ea469
Revises: 
Create Date: 2022-04-13 14:13:57.607122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9944ff8ea469'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channelName', sa.String(length=50), nullable=False),
    sa.Column('profileImageUrl', sa.String(length=255), nullable=False),
    sa.Column('about', sa.String(length=5000), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('hashedPassword', sa.String(length=255), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channelName'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('channels')
    # ### end Alembic commands ###
