"""create document column and index for fts

Revision ID: 21ff198308db
Revises: ca964cd120d4
Create Date: 2024-01-06 15:02:09.041521

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import TSVECTOR

# revision identifiers, used by Alembic.
revision = "21ff198308db"
down_revision = "ca964cd120d4"
branch_labels = None
depends_on = None


class TSVector(sa.types.TypeDecorator):
    impl = TSVECTOR


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "videos",
        sa.Column(
            "document_fts",
            TSVector(),
            sa.Computed(
                "setweight(to_tsvector('english', title), 'A') || setweight(to_tsvector('english', coalesce(description, '')), 'D')",
                persisted=True,
            ),
            nullable=True,
        ),
    )
    op.create_index(
        "document_fts_idx",
        "videos",
        ["document_fts"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("document_fts_idx", table_name="videos", postgresql_using="gin")
    op.drop_column("videos", "document_fts")
    # ### end Alembic commands ###
